### ISSUE TITLE
Feature Request: Get / Set No. Container list

### ISSUE THREAD

**Issue by strongly-typed** [cwapi3d/cwapi3dpython#101]
A recent addition of CW was to add container list number.

I found getters / setters for 

* production_number
* part_number
* assembly_number

but I cannot get/set `container list number` with the API. What a bummer ...

Where can I get/set the `Con-258` by the API?

![image](https://github.com/cwapi3d/cwapi3dpython/assets/1626990/c6c90ef9-fb96-406c-bd4d-ac41ddf10f72)

CW 30, build 374, 2023-12-01

**Comment by strongly-typed** [comment]
There is `ac.get_container_number()` and `ac.get_container_number_with_prefix()` which both are undocumented ...

**Comment by strongly-typed** [comment]
For your convenience, an auto-generated check of your documentation for `attribute_controller` ...

105 methods of 176 documented:  59.7%

Can you please add some more automated QA?
Is all the documentation hand-written and not generated from the API?

| Method | documented |
| -------- | ------- |
| `add_item_to_comment_list` | ❌ |
| `add_item_to_group_list` | ❌ |
| `add_item_to_name_list` | ✔️  |
| `add_item_to_sku_list` | ❌ |
| `add_item_to_subgroup_list` | ❌ |
| `add_item_to_user_attribute_list` | ❌ |
| `clear_errors` | ❌ |
| `delete_additional_data` | ✔️  |
| `delete_item_from_comment_list` | ❌ |
| `delete_item_from_group_list` | ❌ |
| `delete_item_from_sku_list` | ❌ |
| `delete_item_from_subgroup_list` | ❌ |
| `delete_item_from_user_attribute_list` | ❌ |
| `disable_attribute_display` | ✔️  |
| `enable_attribute_display` | ✔️  |
| `get_additional_data` | ✔️  |
| `get_additional_guid` | ✔️  |
| `get_assembly_number` | ✔️  |
| `get_associated_nesting_name` | ❌ |
| `get_associated_nesting_number` | ❌ |
| `get_attribute_display_settings_for_2d` | ❌ |
| `get_attribute_display_settings_for_2d_with_layout` | ❌ |
| `get_attribute_display_settings_for_2d_without_layout` | ❌ |
| `get_attribute_display_settings_for_3d` | ❌ |
| `get_attribute_display_settings_for_container` | ❌ |
| `get_attribute_display_settings_for_export_solid` | ❌ |
| `get_attribute_display_settings_for_framed_wall_axis` | ❌ |
| `get_attribute_display_settings_for_framed_wall_beam` | ❌ |
| `get_attribute_display_settings_for_framed_wall_opening` | ❌ |
| `get_attribute_display_settings_for_framed_wall_panel` | ❌ |
| `get_attribute_display_settings_for_log_wall_axis` | ❌ |
| `get_attribute_display_settings_for_log_wall_beam` | ❌ |
| `get_attribute_display_settings_for_log_wall_opening` | ❌ |
| `get_attribute_display_settings_for_log_wall_panel` | ❌ |
| `get_attribute_display_settings_for_machine` | ❌ |
| `get_attribute_display_settings_for_nesting_element` | ❌ |
| `get_attribute_display_settings_for_nesting_volume` | ❌ |
| `get_attribute_display_settings_for_solid_wall_axis` | ❌ |
| `get_attribute_display_settings_for_solid_wall_beam` | ❌ |
| `get_attribute_display_settings_for_solid_wall_opening` | ❌ |
| `get_attribute_display_settings_for_solid_wall_panel` | ❌ |
| `get_auto_attribute` | ✔️  |
| `get_auto_attribute_name` | ✔️  |
| `get_comment` | ✔️  |
| `get_comment_list_items` | ❌ |
| `get_container_number` | ❌ |
| `get_container_number_with_prefix` | ❌ |
| `get_cutting_set` | ✔️  |
| `get_element_grouping_type` | ✔️  |
| `get_element_material_name` | ✔️  |
| `get_element_type` | ✔️  |
| `get_extended_settings` | ✔️  |
| `get_fastening_attribute` | ✔️  |
| `get_group` | ✔️  |
| `get_group_list_items` | ❌ |
| `get_ignore_in_vba_calculation` | ✔️  |
| `get_last_error` | ❌ |
| `get_list_quantity` | ✔️  |
| `get_machine_calculation_set` | ✔️  |
| `get_machine_calculation_set_machine_type` | ❌ |
| `get_machine_calculation_state` | ❌ |
| `get_name` | ✔️  |
| `get_name_extended_settings` | ✔️  |
| `get_name_list_items` | ✔️  |
| `get_name_process_type` | ✔️  |
| `get_node_symbol` | ❌ |
| `get_output_type` | ✔️  |
| `get_part_number` | ✔️  |
| `get_prefab_layer` | ✔️  |
| `get_prefab_layer_all_assigned` | ✔️  |
| `get_prefab_layer_with_dimensions` | ✔️  |
| `get_prefab_layer_without_dimensions` | ✔️  |
| `get_production_number` | ✔️  |
| `get_sku` | ✔️  |
| `get_sku_list_items` | ❌ |
| `get_standard_element_name` | ✔️  |
| `get_steel_shape_name` | ✔️  |
| `get_subgroup` | ✔️  |
| `get_subgroup_list_items` | ❌ |
| `get_user_attribute` | ✔️  |
| `get_user_attribute_count` | ❌ |
| `get_user_attribute_list_items` | ❌ |
| `get_user_attribute_name` | ✔️  |
| `get_wall_situation` | ✔️  |
| `is_architecture_wall_2dc` | ✔️  |
| `is_architecture_wall_xml` | ✔️  |
| `is_attribute_display_enabled` | ❌ |
| `is_auxiliary` | ✔️  |
| `is_beam` | ✔️  |
| `is_btl_processing_group` | ✔️  |
| `is_caddy_object` | ✔️  |
| `is_circular_mep` | ✔️  |
| `is_connector_axis` | ✔️  |
| `is_container` | ✔️  |
| `is_drilling` | ✔️  |
| `is_envelope` | ✔️  |
| `is_export_solid` | ✔️  |
| `is_floor` | ✔️  |
| `is_framed_floor` | ✔️  |
| `is_framed_roof` | ✔️  |
| `is_framed_wall` | ✔️  |
| `is_hundegger_processing_group` | ✔️  |
| `is_line` | ✔️  |
| `is_log_wall` | ✔️  |
| `is_metal` | ✔️  |
| `is_nesting_parent` | ✔️  |
| `is_nesting_raw_part` | ✔️  |
| `is_node` | ✔️  |
| `is_opening` | ✔️  |
| `is_panel` | ✔️  |
| `is_processing` | ❌ |
| `is_rectangular_mep` | ✔️  |
| `is_roof` | ✔️  |
| `is_roof_surface` | ✔️  |
| `is_solid_floor` | ✔️  |
| `is_solid_roof` | ✔️  |
| `is_solid_wall` | ✔️  |
| `is_surface` | ✔️  |
| `is_wall` | ✔️  |
| `set_additional_data` | ✔️  |
| `set_additional_guid` | ✔️  |
| `set_assembly_number` | ✔️  |
| `set_attribute_display_settings_for_2d` | ❌ |
| `set_attribute_display_settings_for_2d_with_layout` | ❌ |
| `set_attribute_display_settings_for_2d_without_layout` | ❌ |
| `set_attribute_display_settings_for_3d` | ❌ |
| `set_attribute_display_settings_for_container` | ❌ |
| `set_attribute_display_settings_for_export_solid` | ❌ |
| `set_attribute_display_settings_for_framed_wall_axis` | ❌ |
| `set_attribute_display_settings_for_framed_wall_beam` | ❌ |
| `set_attribute_display_settings_for_framed_wall_opening` | ❌ |
| `set_attribute_display_settings_for_framed_wall_panel` | ❌ |
| `set_attribute_display_settings_for_log_wall_axis` | ❌ |
| `set_attribute_display_settings_for_log_wall_beam` | ❌ |
| `set_attribute_display_settings_for_log_wall_opening` | ❌ |
| `set_attribute_display_settings_for_log_wall_panel` | ❌ |
| `set_attribute_display_settings_for_machine` | ❌ |
| `set_attribute_display_settings_for_nesting_element` | ❌ |
| `set_attribute_display_settings_for_nesting_volume` | ❌ |
| `set_attribute_display_settings_for_solid_wall_axis` | ❌ |
| `set_attribute_display_settings_for_solid_wall_beam` | ❌ |
| `set_attribute_display_settings_for_solid_wall_opening` | ❌ |
| `set_attribute_display_settings_for_solid_wall_panel` | ❌ |
| `set_comment` | ✔️  |
| `set_container_number` | ❌ |
| `set_element_grouping_type` | ✔️  |
| `set_element_material` | ✔️  |
| `set_extended_settings` | ✔️  |
| `set_fastening_attribute` | ✔️  |
| `set_floor` | ✔️  |
| `set_group` | ✔️  |
| `set_ignore_in_vba_calculation` | ✔️  |
| `set_layer_settings` | ✔️  |
| `set_list_quantity` | ✔️  |
| `set_log_wall` | ✔️  |
| `set_name` | ✔️  |
| `set_name_extended_settings` | ✔️  |
| `set_name_process_type` | ✔️  |
| `set_node_symbol` | ✔️  |
| `set_opening` | ✔️  |
| `set_output_type` | ✔️  |
| `set_part_number` | ✔️  |
| `set_process_type_and_extended_settings_from_name` | ✔️  |
| `set_production_number` | ✔️  |
| `set_reference_wall_2dc` | ✔️  |
| `set_roof` | ❌ |
| `set_sku` | ✔️  |
| `set_solid_floor` | ✔️  |
| `set_solid_roof` | ✔️  |
| `set_solid_wall` | ✔️  |
| `set_standard_part` | ✔️  |
| `set_subgroup` | ✔️  |
| `set_user_attribute` | ✔️  |
| `set_user_attribute_name` | ✔️  |
| `set_wall` | ✔️  |
| `update_auto_attribute` | ✔️  |

**Comment by Brunner246** [comment]
Hi @strongly-typed 
The generated stuff are just simple stubs without any type hints and description.
Therefore yes, most of it is documented manually. 
We have not updated the documentation for some time, but will do so soon.
