### ISSUE TITLE
[doc] create_rectangular_panel_vectors inconsistent

### ISSUE THREAD

**Issue by strongly-typed** [cwapi3d/cwapi3dpython#102]
The [signature ](https://github.com/cwapi3d/cwapi3dpython/blob/7d7c33dc2780cbb3881b186338caf8c99ed52592/src/element_controller/__init__.py#L218C1-L228C38)mentions `x1` and `z1` whereas the docstring calls these parameters `p2` and `p3`.

For me it is unclear if `z1` defines the direction of the axis (given in absolute COS) or the vector `p1 -> z1` defines the local z axis.

**Comment by Brunner246** [comment]
The docstrings are incorrect. ```p2``` should be named ```xl``` and ```p2``` should be named ```zl``` 

xl = direction of length axis
zl = direction of height axis

![image](https://github.com/cwapi3d/cwapi3dpython/assets/71121348/ad5cf684-431f-4752-a4d6-8aba93735b18)

we'll fix that
