### ISSUE TITLE
Where is the source code of cwapi3dpython ?

### ISSUE THREAD

**Issue by Aupire** [cwapi3d/cwapi3dpython#104]
Hi everyone, 
Maybe a stupid question : where is the source code of class of your package ? 
 
In class "point_3d", we have only : 
```python
class point_3d():

    def __init__(self, x: float, y: float, z: float) -> None:
        self.x = x
        self.y = y
        self.z = z

    def __add__(self, another_point_3d):
        """adds two points

        Args:
            point_3d (point_3d): a second point

        Returns:
            point_3d: a third point
        """
```
Where id the code of the __add__ method ?

**Comment by Brunner246** [comment]
Hi @Aupire 
This are just "Stubs" for getting autocompletion. 
The source is in C++ we "just" expose it to python.
