### ISSUE TITLE
get_actual_physical_volume

### ISSUE THREAD

**Issue by sam-snodgrass** [cwapi3d/cwapi3dpython#106]
Hello, I have a question about the get_actual_physical_volume method in geometry controller. How does it differ exactly from the get_volume method? From my testing, the volumes of the drilling axes inside of the element are subtracted from the volume of the element as if they were physically drilled. How then do connector axes affected the measured volume? Especially the more complex ones containing counterbores and various drilling diameters.

**Comment by jspaquet** [comment]
get_actual_physical_volume subtracts all negative geometry operations on the element. This includes end-types, drillings, connectors, openings, and MEP elements. Looking at the actual code it looks like this takes into account different drilling bodies in a connector. I would think it also takes counterbores into account but I am not 100% sure simply looking at our code.

**Comment by pierreBodineau** [comment]
I was going to make a pull request to add your answer in the docstring. So that everybody would benefit from the info, and you wouldn't have this question asked again. But, as I understand with your new parser thing, it is not possible anymore ?

**Comment by Brunner246** [comment]
@pierreBodineau you can still do that. We have options to not override existing functions in the python stubs src.

**Comment by pierreBodineau** [comment]
Thanks @Brunner246. This is good news!
