### ISSUE TITLE
How do we set an export volume in Cadwork with Python ? Is it "export solid" as I read in the documentation ? 

### ISSUE THREAD

**Issue by Aupire** [cwapi3d/cwapi3dpython#109]
Hi, 
How do we set an export volume in Cadwork with Python ? Is it "export solid" as I read in the documentation ? 

Thanks !

**Comment by Brunner246** [comment]
Hi,

You are right, it is export solid 

`def create_auto_export_solid_from_standard(a_elements: List[int]) -> int:`

`def create_auto_export_solid_from_standard_with_reference(a_elements: List[int], a_reference_id: int) -> int:`

`def set_export_solid_contents(a0: int, a1: List[int]) -> None:`

`def get_standard_export_solid_list() -> List[str]:`

`def get_export_solid_content_elements(a_id: int) -> List[int]:`
