### ISSUE TITLE
Set Create process?

### ISSUE THREAD

**Issue by NOPKGer** [cwapi3d/cwapi3dpython#111]
Hey,
Is it possible to control the following option via the API?

![Screenshot 2024-01-22 134955](https://github.com/cwapi3d/cwapi3dpython/assets/113988018/d7cbca8f-f757-4ec3-9643-2227a8691773)

By default is in singel part and I want to add composite.

**Comment by Brunner246** [comment]
so far this is not possible via `cwapi3d`

**Comment by NOPKGer** [comment]
ok, Thanks for the info
