### ISSUE TITLE
Allow more joint types to be assigned over the `element_controller`

### ISSUE THREAD

**Issue by chenkasirer** [cwapi3d/cwapi3dpython#121]
Would it be possible to add more joint types to be assigned with an API call, similarly to [`cut_elements_with_miter()`](https://docs.cadwork.com/projects/cwapi3dpython/en/latest/documentation/element_controller/#element_controller.cut_elements_with_miter)

Specifically, would be cool to be able to assign:
1. L/T-Butt
2. X/T/L-Lap

Thank you!

**Comment by Brunner246** [comment]
see newly added methods in https://github.com/cwapi3d/cwapi3dpython/blob/main/src/element_controller/__init__.pyi#L1861

**Comment by chenkasirer** [comment]
Thank you so much!
