### ISSUE TITLE
Is it possible to get the true/false status of the user attributes with the Python API?

### ISSUE THREAD

**Issue by d2p-m7** [cwapi3d/cwapi3dpython#124]
![grafik](https://github.com/cwapi3d/cwapi3dpython/assets/159874947/b0444375-d04e-4333-967c-e70a0da8f2dc)

_gm7

**Comment by Brunner246** [comment]
status => `WIP`

**Comment by Brunner246** [comment]
will be available within next update @d2p-m7 
`is_attribute_visible_in_modify_window` 
`set_attribute_visibility_in_modify_window`

**Comment by Brunner246** [comment]
https://github.com/cwapi3d/cwapi3dpython/blob/011f154d60feec40ec3cc58c570e99dd942afb0c/src/attribute_controller/__init__.pyi#L1753

https://github.com/cwapi3d/cwapi3dpython/blob/011f154d60feec40ec3cc58c570e99dd942afb0c/src/attribute_controller/__init__.pyi#L1763
