### ISSUE TITLE
Connector Axis import from file

### ISSUE THREAD

**Issue by sam-snodgrass** [cwapi3d/cwapi3dpython#134]
Hello,
what is the required file type and format for this method in connector_axis_controller.import_from_file?

```
def import_from_file(a0: str) -> None:
    """import from file
    Args:
        a0 ( str): a0

    Returns:
        None
    """
```

Every input I've attempted so far has completely crashed the application

**Comment by jspaquet** [comment]
Hey Sam,

I'll send you the info via email. 

Thanks,
