### ISSUE TITLE
IfcElementAssembly - Missing in ifc2x3_element_type

### ISSUE THREAD

**Issue by MoritzNiebler** [cwapi3d/cwapi3dpython#179]
Hello together, 

I am missing the IfcElementAssembly as an IFC-Type.
If i get the ifc type from a container element it is none, although it is set as IfcElementAssembly. 
When setting the name of a container with the attribute controller set_name() method the IFC Type goes missing,
and would need to be set again as IfcElementAssembly. 
Which seems to be missing in the API as an IFC-Type. 

Would be really much appreciated if this could be added. 

Best Moritz

**Comment by Brunner246** [comment]
Hi @MoritzNiebler 

That's right, we'll add that asap.

**Comment by Brunner246** [comment]
Done (will be available within the next minor version (live-update))
