### ISSUE TITLE
display_simple_menu - no exit from custom menu

### ISSUE THREAD

**Issue by nrogeau** [cwapi3d/cwapi3dpython#184]
Hi, 

When running the examples presented in [Menu Controller](https://docs.cadwork.com/projects/cwapi3dpython/en/latest/examples/menu_example/), it seems there is no way to exit the custom menus generated by the function "display_simple_menu".

In the code extract below, breaking the while loop with "Return", does not stop the display of the custom menu.

while True:
    menu = mc.display_simple_menu(menu_options)
[...]
   if menu == 'Return':
        break

**Comment by Brunner246** [comment]
Hi @nrogeau 

Have you run the example from the idle shell ?
if so, run it from api directory. `userprofil_30\3d\API.x64`

**Comment by nrogeau** [comment]
Hi @Brunner246,

Thank you for your reply.
I am indeed running the example from the idle shell.
Do you mean the Python file should be located in the API.x64 folder?
I tried running it from there and also by changing the working directory like below but without success:

```
import os
import menu_controller as mec 
import utility_controller as uc
import cadwork

os.chdir('C:\\Users\\Public\\Documents\\cadwork\\userprofil_30\\3d\\API.x64')

menu_options = 'Foo', 'Bar', 'Baz', '', 'Return'

menu = mec.display_simple_menu(menu_options)
while True:
    if menu == 'Foo':
        uc.print_error('You pressed Foo')

    elif menu == 'Bar':
        uc.print_error('You pressed Bar')

    elif menu == 'Baz':
        uc.print_error('You pressed Baz')

    elif menu == 'Return':
        break


```

**Comment by Brunner246** [comment]
@nrogeau running the `display menu` from tkinter IDLE will not work properly. 

1. Create directory in `userprofil_30\3d\API.x64\simpleMenu`  
2. Create a python file (e.g. `simpleMenu.py`) in that directory
3. launch cadwork
4. click button in plugin bar

if you dont see the plugin name in the plugin bar, check if you show the bar itself.

<img width="278" alt="image" src="https://github.com/cwapi3d/cwapi3dpython/assets/71121348/fb4fc506-8951-461f-96d6-08a4da5e399f">



see also:
https://docs.cadwork.com/projects/cwapi3dpython/en/latest/get_started/

**Comment by nrogeau** [comment]
Hi @Brunner246,

Okay, I understand. Thank you for the explanation, it worked when launching the script from the button.
