### ISSUE TITLE
cwapi3d imports

### ISSUE THREAD

**Issue by ivan-modelical** [cwapi3d/cwapi3dpython#2]
only 3 classes are available when importing 'cadwork' module in a python session:

>>> dir(cadwork)
__doc__ __loader__ __name__ __package__ __spec__ **element_type point_3d rgb_color**

controller methods that return other classes don't work, i.e: **element_module_properties**

Are you planning on adding the rest of the bindings?

**Comment by jspaquet** [comment]
We do have plans to add the rest of the interfaces. Unfortunately some of them are quite difficult to implement _easily_ in Python since they are tricky to use even from C++.

What are you trying to do with element_module_properties?

**Comment by ivan-modelical** [comment]
Hi @jspaquet 
It was just an example class thta we found we couldn't access. Our short term needs with the API would be to be able to place wall axis and reference face programatically with data from BIM model. 

Anyways, the more you open the API the more possiblities that will surface.
