### ISSUE TITLE
delete_scene does not work

### ISSUE THREAD

**Issue by adrimg89** [cwapi3d/cwapi3dpython#219]
Hello everybody.

I have a problem with the delete_scene module.
When I call the function, the scene is apparently deleted (it is not at the scene bar), but if I get the scene list, it still appears in the list. If I try to create a new scene with the same name as the deleted one, the program shows a text like 'This name is already in use'.
It looks like the function only hides the scene, not delete it.

I tried with two different models and the same issue happens.

Does anyone have the same problem?

**Comment by Brunner246** [comment]
this will be fixed within the next cadwork (SP2024) live-update

**Comment by adrimg89** [comment]
Hi @Brunner246 , thank you very much for your fast reply!
When is that update expected?

Thank you!
