### ISSUE TITLE
Error retrieving element module properties of an element

### ISSUE THREAD

**Issue by JeromeJ-L** [cwapi3d/cwapi3dpython#27]
Hello, I'm not sure if this is a bug, however here is my session with the python interpreter :

`import element_controller as ec

def activeElements():
    return ec.get_active_identifiable_element_ids()

for e in activeElements():
    eProps = ec.get_element_module_properties_for_element(e)

	
Traceback (most recent call last):
  File "<pyshell#6>", line 2, in <module>
    eProps = ec.get_element_module_properties_for_element(e)
TypeError: Unable to convert function return value to a Python type! The signature was
	(arg0: int) -> element_module_properties`

I have a good idea of API to help the creation of module element that I had suggested in webinar, if I manage to recover the properties module elements and to assign them, it would certainly be possible for me to show this API thanks to your job.

Maybe I forgot to import a module?
Regards,
jerome

**Comment by Brunner246** [comment]
Hi,
Currently, the functionality for the element module properties are not yet implemented in the Python API.
What exactly do you want to do?
Can you describe a specific use case?

**Comment by Brunner246** [comment]
@JeromeJ-L 
@fbpyr
@ivan-modelical
@louistrue

The element module properties are implemented in the newest build of the py package (from cwapi3d 1.3.1) 
**Attention, the package is created for version 29 of cadwork.**

### usage example 
```python
import cadwork as cw
import element_controller as ec
import utility_controller as uc

elems = ec.get_active_identifiable_element_ids()

# method 1
for elem in elems:
    props = ec.get_element_module_properties_for_element(elem)
    if props.is_distribute_in_axis_direction():
        props.set_distribute_in_axis_direction_use_number(True, 4)
    else:
        props.set_distribute_in_axis_direction(True, 100.)

    ec.set_element_module_properties_for_elements([elem], props)


# method 2
for elem in elems:
    module_type = ec.get_element_module_properties_for_element(elem)
    if module_type.is_distribute_in_axis_direction():
        print(True)
        cw.element_module_properties.set_bottom_plate(module_type, True)
    else:
        print(False)
        cw.element_module_properties.set_top_plate(module_type, True)
        
    ec.set_element_module_properties_for_elements([elem], module_type)
```
