### ISSUE TITLE
Aligned Bounding Boxes in cwapi?

### ISSUE THREAD

**Issue by fbpyr** [cwapi3d/cwapi3dpython#28]
After having a brief chat with @Brunner246 about bounding boxes, 
I was wondering if we could have aligned bounding boxes in 
cadwork api for rotated elements?

For orthogonal elements I would use a simple bbox from here: 
https://github.com/fbpyr/cw_toolbox/blob/cec6821179de0a9fff7c907b0fbcbff4654be767/helpers/bbox.py#L20

But  for rotated/tilted elements this obviously does not return the 
needed aligned bbox. Ideally these Bounding boxes could also be combined. 
A typical use case for this would be a slanted roof with a row or rotated beams: 
Ideally one could access the aligned bbox of each beam 
and be able to be combine the bounding boxes into one:

![image](https://user-images.githubusercontent.com/73931454/161049469-bc0a8422-e0ab-4719-adb6-54cca31646f1.png)

**Comment by Brunner246** [comment]
Hi @fbpyr 
new function added for version 29.
also available for version 28 with build 425 

````python
def create_bounding_box_local(element:int, elements:List[int]) -> int:
    """create a bounding box that is aligned to a reference element. 
    The bounding box includes all elements contained in the list.

    Args:
        element (int): element ID reference element
        elements (List[int]): element IDs

    Returns:
        int: element ID bounding box
    """


def create_bounding_box_global(elements: List[int]) -> int:
    """create a bounding box that is aligned to the global coordinate system.

    Args:
        elements (List[int]): element IDs

    Returns:
        int: element ID bounding box
    """

```

**Comment by fbpyr** [comment]
amazing!! 🎉 
this is a great addition to the api!!
( ..and also will save me quite some work ☺️ )
