### ISSUE TITLE
Debugging Python Addins

### ISSUE THREAD

**Issue by ivan-modelical** [cwapi3d/cwapi3dpython#3]
Hi @jspaquet,

Is there any stack trace or log where one can trace what crashes CADWORK when using the python API?

I'm having problems using Pandas (we are using it for an excel io addin) where after the first run CADWORK crashes, and I can't find any info on the possible errors.

Using CADWORK v28 Build 238

Thanks in advance!

**Comment by Brunner246** [comment]
Did you open the console while running the program? 
User Test -> User Profile -> Test options -> Console

**Comment by ivan-modelical** [comment]
> Did you open the console while running the program? User Test -> User Profile -> Test options -> Console

Hi @Brunner246 , thank you for your response. I don't follow what you say.. what do you mean? How do you setup de "Test option"?

I have been using CADWORK mostly through the Python API so I am not familiar with the UI

**Comment by louistrue** [comment]
![1](https://user-images.githubusercontent.com/78563314/135451567-f1653b02-eabb-4c5a-bbe2-bf7aad1521fe.png)
![2](https://user-images.githubusercontent.com/78563314/135451754-5abd2016-33b1-4ea4-90c3-18e4be7c7e25.png)
![3](https://user-images.githubusercontent.com/78563314/135451757-b73e7a1e-af94-4cbc-a13a-80724134a3c2.png)
![4](https://user-images.githubusercontent.com/78563314/135451759-c8b5ec33-8085-424b-938d-60e82d4b9e4e.png)

**Comment by louistrue** [comment]
@ivan-modelical

**Comment by ivan-modelical** [comment]
Awesome @louistrue!
Will try again with Pandas on the latest build and let you know!

Thx

**Comment by ivan-modelical** [comment]
Console does not show any error on the script, so I guess its something related to the embedded Python in Cadwork. Can anybody replicate this problem using pandas?
![2021-09-30 16_13_41-ScreenToGif - Editor](https://user-images.githubusercontent.com/72398811/135472004-a8f4f84b-c2a6-4975-a05d-aabe7f6e5486.png)

**Comment by Brunner246** [comment]
Hi @ivan-modelical 

Pandas accesses Numpy. Numpy causes problems when the module is embedded. As an alternative you could use openpyxl. 

![image](https://user-images.githubusercontent.com/71121348/135873644-956fa72b-5751-4233-bcb8-8a23fb9496e7.png)

**Comment by ivan-modelical** [comment]
Thanks @Brunner246 !! Good to know.

Currently I'm using [pylightxl](https://pylightxl.readthedocs.io/en/latest/index.html) which is lightweight and pure python with no dependencies. For pure data IO is perfect.

**Comment by Brunner246** [comment]
@ivan-modelical 
Fyi..

This link will take you to the Python Guide for cadwork. The guide is "under construction" and will be updated continuously. 

https://python.cadwork.dev/en/latest/
