### ISSUE TITLE
Add extra references

### ISSUE THREAD

**Issue by Pvmdark** [cwapi3d/cwapi3dpython#64]
### Discussed in https://github.com/cwapi3d/cwapi3dpython/discussions/57

<div type='discussions-op-text'>

<sup>Originally posted by **Pvmdark** January 10, 2023</sup>
Dear,

Is it possible to add the references below:
Element controller convert rectangular beam to circular beam
The command round machine rough part with options Positive/negative height axis and positive/negatie width axis
Checking on defective parts and option to activate them.
Option to add command surfaces to volumes

Kind regards,
Branko</div>

**Comment by Pvmdark** [comment]
@Brunner246  any idea whenever this is ready?

**Comment by Brunner246** [comment]
The tasks are in our backlog. They will be added in the next sprints.
The task "_Checking on defective parts and option to activate them_" can not be implemented.

**Comment by Brunner246** [comment]
@Pvmdark 

````python
element_controller.extrude_surface_to_auxiliary_vector(...)
element_controller.extrude_surface_to_beam_vector(...)
element_controller.extrude_surface_to_panel_vector(...)
````
