### ISSUE TITLE
Plugin can't find

### ISSUE THREAD

**Issue by Rainingat** [cwapi3d/cwapi3dpython#67]
I want to make the API and followed your instructions, but when I finished all the steps, i can't find the icon, it's so weired, how can I solve this problem ?

**Comment by Pvmdark** [comment]
Make sure the folder of your plugin and python file have the same name, the icon itself must have the name "icon.png".

**Comment by Brunner246** [comment]
..\userprofile_30\3d\API.x64 (Directory)

- **MyFirstScript** (Folder)
  - **MyFirstScript**.py (Python File)
  - **Icon**.png (Plugin Icon, size ~30x30 pixel)
