### ISSUE TITLE
Python Documentation unclear

### ISSUE THREAD

**Issue by claudiubrb** [cwapi3d/cwapi3dpython#68]
I found all the available controllers and the methods in each one and what input it requires which sometimes work but there is no explanation of what the method does. I have instances where I cannot deduce from the method name what I can do with it and no explannation for it. Is there documentation related to the methods avaialable somewhere ? I think it's impossible to grow a community around this without further explanation of what can be done.
In my case I'm working with IFC files comming from a 3rd party which have parameters ( or attributes) which I can see in the IFC browes but I cannot access their values which , for serval, I want to map into cadwork attributes. is there a way available for this ? 

Thank you, 

much apreciated any answers

**Comment by Brunner246** [comment]
@claudiubrb 

https://docs.cadwork.com/projects/cwapi3dpython/en/latest/

**Comment by Brunner246** [comment]
Hi Claudiu
Mapping of IFC Attributes is at the moment just possible via Ifc Property Mapper in 3d. 
If you get the same properties, you can save the mapping configuration and load it for the mapping process.
We are constantly working on the implementation of new features. The modifier functions you mentioned are in our backlog.

**Comment by Brunner246** [comment]
Hi Claudiu,
cadwork will release version 30 in the near future.
I recommend you to update at least to version 29.
