### ISSUE TITLE
attribute_controller: Docstring return type correction

### ISSUE THREAD

**Issue by flashsturz** [cwapi3d/cwapi3dpython#69]
In _attribute_controller_, the functions `get_element_material_name` and `get_prefab_layer` are said to return strings from their function declaration type hints, but the function docstrings states in both cases that the return value is a bool.

Given the function name, I think these should indeed return strings, so you might have to correct the type hints in the _attribute_controller_

**Comment by Brunner246** [comment]
Which package version are you using ? 

Docstrings should be correct. 

https://github.com/cwapi3d/cwapi3dpython/blob/main/src/attribute_controller/__init__.py#L581

https://github.com/cwapi3d/cwapi3dpython/blob/main/src/attribute_controller/__init__.py#L568

```python
>>> import cadwork
>>> import element_controller as ec
>>> import attribute_controller as ac

>>> element_ids = ec.get_active_identifiable_element_ids()
>>> for element_id in element_ids:
             print(ac.get_prefab_layer(element_id))

# string output 
WithDimensions[2] WithoutDimensions[] ShowAttributes[2]
WithDimensions[0] WithoutDimensions[1,-1] ShowAttributes[0]
```

same for 
```python
...
>>> for element_id in element_ids:
             print(ac.get_element_material_name(element_id))

# string output
Fermacell st 2.L
Fichten-Duo-Balken C24 nsi
```

**Comment by flashsturz** [comment]
What I meant is that the docstrings are wrong in that they state, that the return value of the functions should be a bool, whereas in reality, the return values are strings.
Example for _get_prefab_layer_
**Docstring:**

>     """Gets the element prefab layer
> 
>     [:information_source: Available for script filled attributes](#){.mark-text}
> 
>     Args:
>         element (int): element ID
> 
>     Returns:
>         bool: element prefab layer
>     """

**Actual return type:**

> string
