### ISSUE TITLE
is_beam() issue

### ISSUE THREAD

**Issue by BogdanERG** [cwapi3d/cwapi3dpython#78]
Hi,

I've tried to sort elements by type in a script but it seems that all elements return True on is_beam attribute.
I just made a test, trying to understand where this problem came from.

Here is the code where I double check with element type description function:

`el_active = element_controller.get_active_identifiable_element_ids()`
`for ceva in el_active:`
       `    print(element_controller.get_element_type_description(ceva))`
       `    print(attribute_controller.is_beam(ceva))`

and I randomly take 5 elements (2 auxiliary, 1 floor, 1 opening and 1 beam)
All of them return True on is_beam and all of them return Beam on element type.

![el](https://github.com/cwapi3d/cwapi3dpython/assets/135235091/3d1b6b8d-fea3-464f-9730-84bea1bf7970)
![return](https://github.com/cwapi3d/cwapi3dpython/assets/135235091/af34eb24-1b4f-4338-9325-1838d7c8b2d4)

There is something I can do to make this right ? 
I don't recall having issues with this function in the past.

**Comment by Brunner246** [comment]
Hi @BogdanERG 

This is due to polymorphism, since the elements are in the same inheritance hierarchy almost everything is a beam. 
**You better use the following functions to get a better result.**

```python
active_element_ids = ec.get_active_identifiable_element_ids()
for element_id in active_element_ids:
    cw_element_type = ac.get_element_type(element_id)
    if cw_element_type.is_rectangular_beam():
        print(f'Element {element_id} is a beam')
    elif cw_element_type.is_drilling_axis():
        print(f'Element {element_id} is a drilling')


# output
Element 558844 is a drilling
Element 548541 is a beam
# the third element which is an auxiliary is not considered during that check
# since the "filter" is set for rectangular beam and drilling axis
```

<img width="748" alt="Screenshot 2023-06-13 095530" src="https://github.com/cwapi3d/cwapi3dpython/assets/71121348/be75517c-e35c-4e9c-97ee-c208350227de">

**Comment by BogdanERG** [comment]
I've tried your way but it seems like something is not right.

![image](https://github.com/cwapi3d/cwapi3dpython/assets/135235091/8f30146f-6415-4df5-81e9-d13a9dad01e1)

Do I miss something ?

**Comment by Brunner246** [comment]
You have to import the modules into your namepsace
```python
import cadwork
import element_controller as ec
import attribute_controller as ac

... your code ...
````

**Comment by BogdanERG** [comment]
`import element_controller as ec 
import attribute_controller as ac
`

**Comment by BogdanERG** [comment]
Yes, I had the ec and ac but didn't have `import cadwork`.

Thank you for response.
