### ISSUE TITLE
DXF export

### ISSUE THREAD

**Issue by Beltashazar** [cwapi3d/cwapi3dpython#81]
I am wondering if anyone knows how DXF's can be exported through the API? I cannot find anything in the API reference for the function, but it can be done manually in CadWork.

Thanks in advance!

**Comment by Brunner246** [comment]
Hi @Beltashazar 
DXF Export is not possible via API.
If this would be wanted, please start a request.

**Comment by Beltashazar** [comment]
Hey @Brunner246
Thanks for the information! What is the "official" way of starting a request for something like this? Is that through Github or is it by e-mailing technical support, or is there some other way of requesting an update?

Thanks again!

**Comment by Brunner246** [comment]
@Beltashazar via GitHub will be the best way. 
i set the label to request.

**Comment by Beltashazar** [comment]
Thank you!

**Comment by Beltashazar** [comment]
Just keeping this open. Would still love to have this feature!

**Comment by Brunner246** [comment]
@Beltashazar 
Can you please describe what you want to do with it?
Is it about 2D or 3D DXF export?

**Comment by Beltashazar** [comment]
@Brunner246 We currently export 2D shop prints from 3D with containers for all of our welded steel assemblies. We also export DXF files for each part of a welded assembly to give to our steel fabricator. This is really helpful for them and us as it speeds up the fabrication lead time because they do not need to make a DXF file for their CNC machines. We currently export the DXF files manually because, as far as I have been able to find, there is no way to do this through the API.

**Comment by Brunner246** [comment]
@Beltashazar 
The API can just be used from 3D. 
DXF's are generated from 2D drawings, which is not possible with the API.
