### ISSUE TITLE
Feature Request: Python API Extension for Automatic Conversion of Enclosed Surfaces to Volume

### ISSUE THREAD

**Issue by Christoph-Merk** [cwapi3d/cwapi3dpython#87]
Cadwork supports manual conversion of surfaces that form a closed volume into a volume.  To enhance the functionality and efficiency of Cadwork's Python API, I propose the addition of a new function, tentatively named "convert_multiple_surfaces_to_volume", which would programmatically perform this conversion.

convert_multiple_surfaces_to_volume(elements: List[int]) -> int

Parameters:
elements: A list of element IDs representing the surfaces that enclose a volume. This parameter is required and does not have a default value.
Returns:
The function returns a new element ID that represent the generated volume.

**Comment by Christoph-Merk** [comment]
Is this function available? I see it's in the documentation but I get an error. I use cadwork30 and there's no update available.

`                print(ids)
                roof_id = ec.convert_surfaces_to_volume(ids)`
                
![image](https://github.com/cwapi3d/cwapi3dpython/assets/113347464/90ef9b7e-cda9-4321-bca8-bdbaf53e848f)

**Comment by Brunner246** [comment]
Looks like your build is too small. 

Please contact your cadwork support team to get the SP2024 version.
