### ISSUE TITLE
VBA - create standard, add processing and create as element  - Not Working as Expected

### ISSUE THREAD

**Issue by Christoph-Merk** [cwapi3d/cwapi3dpython#88]
![vba_drill_cad](https://github.com/cwapi3d/cwapi3dpython/assets/113347464/1e100276-a5d8-426e-bbed-a6f54a6def1f)
![vba_drill](https://github.com/cwapi3d/cwapi3dpython/assets/113347464/7a17f788-f97d-44ff-8511-c73f35c15783)
![vba_code](https://github.com/cwapi3d/cwapi3dpython/assets/113347464/90fcdc4f-739e-4d5f-bf27-ac3028ecb54b)

When using the create_standard_vba function, the function is expected to create a new VBA representing a drilling with specific dimensions. Despite the function's apparent success in creating a VBA, subsequent attempts to set its parameters (such as section diameter and overall diameter) lead to errors, and the created VBA cannot be assigned to an element ID.

I am seeking assistance to:
1. Understand how to correctly set the parameters for the created VBA.
2. Correct the code or process to allow for the successful creation and manipulation of VBAs.

**Comment by Brunner246** [comment]
```python
import cadwork
import connector_axis_controller

>>>connector_axis_controller.create_standard_connector("MyScrew", cadwork.point_3d(0.,0.,0.), cadwork.point_3d(0.,0.,100.)) # standard connector must exist in your 3d document
841935134
>>>connector_axis_controller.set_bolt_length(841935134, 400.0)
>>>connector_axis_controller.get_bolt_length(841935134)
400.0
>>>connector_axis_controller.update_axis_cutting_ability([841935134])
>>>connector_axis_controller.get_section_count(841935134)
4
>>>section : int = 2
>>>connector_axis_controller.set_section_diameter(841935134, section, 40.0)
>>>connector_axis_controller.get_section_diameter(841935134, section)
40.0
```

![image](https://github.com/cwapi3d/cwapi3dpython/assets/71121348/a9e30033-3cbd-4efe-a777-f1a9c85cce13)
