### ISSUE TITLE
export solids are not imported

### ISSUE THREAD

**Issue by NOPKGer** [cwapi3d/cwapi3dpython#90]
The Export Solids are not loaded into the file, when I´m using "import_3dc_file(file)".

**Comment by NOPKGer** [comment]
Is there an estimate if and when the bug will be fixed? best regards

**Comment by Brunner246** [comment]
@NOPKGer 
The behaviour is also the same in 3d, that the export solids are not imported. 
I will create a separate function with import options for 3d/3dc files.

**Comment by Brunner246** [comment]
this will be available within the next API release (SP 2024)

```python
>>>import cadwork
>>>import file_controller

>>>import3dc_options = cadwork.import_3dc_options()
>>>import3dc_options.get_import_export_solids()
False
>>>import3dc_options.set_import_export_solids(True)
>>>import3dc_options.get_import_export_solids()
True
>>>import3dc_options.set_reset_position_numbers(False)

>>>file_controller.import_3dc_file_with_options(r"path/to/your/file.3dc", import3dc_options)
````

**Comment by NOPKGer** [comment]
Nice, thanks a lot
