### ISSUE TITLE
Missing Auto Attribute functions

### ISSUE THREAD

**Issue by Beltashazar** [cwapi3d/cwapi3dpython#92]
Hello,

I was attempting to write a script for the auto attribute feature and I am getting an error that the functions cadwork.get_auto_attribute_elements() and cadwork.set_auto_attribute() are not present in the cadwork library. If they are somewhere else it would be great to know where and have the documentation updated.

Thanks!
Shaun

**Comment by Brunner246** [comment]
https://docs.cadwork.com/projects/cwapi3dpython/en/latest/auto_attributes/

**Comment by Beltashazar** [comment]
Michael,

I followed some of the examples on this page and found that my attribute was not filling. I took the code and put it in the python console and was getting errors that the functions don't exist in the cadwork library...

Shaun

**Comment by Brunner246** [comment]
Hi Shaun,

you have to use it like this:

<img width="801" alt="image" src="https://github.com/cwapi3d/cwapi3dpython/assets/71121348/92de4e09-bbd9-415f-ae11-a9ad16926cda">

<img width="418" alt="image" src="https://github.com/cwapi3d/cwapi3dpython/assets/71121348/d6e1689b-935f-4285-ac7a-fda92bb69df5">

Please provide your code or snippets of it.
