### ISSUE TITLE
Feature Request: Convert Drilling Axis to Circular Beam

### ISSUE THREAD

**Issue by sam-snodgrass** [cwapi3d/cwapi3dpython#96]
Would it be possible to add a method to the element controller that converts a drilling axis to a circular beam? 

<img width="122" alt="image" src="https://github.com/cwapi3d/cwapi3dpython/assets/145357460/3bb41535-0bf4-430b-b498-b9e0e9823206">

The functionality already exists in the application, this is what I would like the method to do.

ex: 
convert_drilling_to_circular_beam(drilling_element_ids: List[int])

**Comment by jspaquet** [comment]
I thought we had something like that already. Let me verify. If not I'll add it this week. 

If you need an alternative without waiting you can always loop over the elements and create new ones on top with p1/p2/etc.

**Comment by sam-snodgrass** [comment]
Excellent, thank you. As an additional question, do you know of a way to rapidly select all pieces in collision with an element? I know there's the check_if_elements_are_in_collision method in the element controller but this would become quite slow in the case of larger files with thousands of elements.

**Comment by pierreBodineau** [comment]
Hi,
Just to clarify:
I see "closed as completed" so I guess the change has been made. But I don't see a linked pull request and no change in the documentation.
So, has the API been updated ? In which build ? And will the documentation be updated ?
Or is it more a "closed as not planned" ?

**Comment by jspaquet** [comment]
It should be available on V30 build 402+ in element_controller.convert_drilling_to_circular_beam(List). We are currently implementing an automated updating mechanism for the documentation so there might be a delay before it appears on there.

**Comment by pierreBodineau** [comment]
Great. Thanks for the clarification.
