### ISSUE TITLE
Feature request: ac.set_framed_wall(element)

### ISSUE THREAD

**Issue by strongly-typed** [cwapi3d/cwapi3dpython#99]
There are getters like [`ac.is_framed_wall()`](https://docs.cadwork.com/projects/cwapi3dpython/en/latest/documentation/attribute_controller/?h=framed+wall#attribute_controller.is_framed_wall) but I did not find the corresponding setters. I only found [`ac.set_wall()`](https://docs.cadwork.com/projects/cwapi3dpython/en/latest/documentation/attribute_controller/?h=framed+wall#attribute_controller.set_wall) but did not find `ac.set_framed_wall(element)`. Could you please add this or tell me how to do it?

When you set the wall to framed wall in the UI there is an option to "align axes of architectural elements according to specifications for element module". This should be please possible with the API as well.

![image](https://github.com/cwapi3d/cwapi3dpython/assets/1626990/557c4a57-de81-4704-9abe-13511302ae64)

CW 30, build 374, 2023-12-01

**Comment by Brunner246** [comment]
@strongly-typed 

This function is under the name ```set_wall``` available. 

```python
import cadwork
import attribute_controller as ac
import element_controller as ec
import geometry_controller as gc

element_ids = ec.get_active_identifiable_element_ids()
ac.set_wall(element_ids) # this sets the wall type to framed wall

gc.auto_regenerate_axes(element_ids) # regenerate if needed

```

**Comment by strongly-typed** [comment]
Thank you @Brunner246 for the hint, but it unfortunately does not work.

When I call the function from a script I am stuck with `Add axis 2 points` in the info line which I cannot exit.

Also, could you please match the naming of the setter to the getter?
If I understand you correctly, the table currently is like this?

| Setter | Getter |
| --- | --- |
| [`set_log_wall`](https://github.com/cwapi3d/cwapi3dpython/blob/7d7c33dc2780cbb3881b186338caf8c99ed52592/src/attribute_controller/__init__.py#L740) | [`is_log_wall`](https://github.com/cwapi3d/cwapi3dpython/blob/7d7c33dc2780cbb3881b186338caf8c99ed52592/src/attribute_controller/__init__.py#L357)
| [`set_solid_wall`](https://github.com/cwapi3d/cwapi3dpython/blob/7d7c33dc2780cbb3881b186338caf8c99ed52592/src/attribute_controller/__init__.py#L959) | [`is_solid_wall`](https://github.com/cwapi3d/cwapi3dpython/blob/7d7c33dc2780cbb3881b186338caf8c99ed52592/src/attribute_controller/__init__.py#L343) |
| [`set_wall`](https://github.com/cwapi3d/cwapi3dpython/blob/7d7c33dc2780cbb3881b186338caf8c99ed52592/src/attribute_controller/__init__.py#L732) | [`is_wall`](https://github.com/cwapi3d/cwapi3dpython/blob/7d7c33dc2780cbb3881b186338caf8c99ed52592/src/attribute_controller/__init__.py#L316) | 
| [`set_wall`](https://github.com/cwapi3d/cwapi3dpython/blob/7d7c33dc2780cbb3881b186338caf8c99ed52592/src/attribute_controller/__init__.py#L732) | [`is_framed_wall`](https://github.com/cwapi3d/cwapi3dpython/blob/7d7c33dc2780cbb3881b186338caf8c99ed52592/src/attribute_controller/__init__.py#L329) |

Does not feel intuitive for me, unfortunatley.

**Comment by Brunner246** [comment]
Thanks for the Bug report, we'll fix that.

I'll create an alias for:
 `set_wall` => `set_framed_wall` 
`is_wall` => `is_framed_wall` 

We are currently working on a reliable parser that generates the stubs and docs automatically. The next package we release will be complete.
